### ISSUE TITLE
Message: "could not update aspects" when trying to add Email Template aspect.

### ISSUE THREAD

**Issue by rgiaviti** [mxc/alfresco-emaildocuments-share#3]
I have installed the module following this instructions here: http://www.jumpingbean.biz/alfresco-email-documents-action-project

The installation worked fine. Only a message "Unable to load module details from property file" appears when installing the module "Alfresco Repository. But I ignored the message.

When I accessed Alfresco Share and added the aspects "Email Template" and "Enable email document action", after I clicked in Apply Changes, the message could not update aspects appeared. The menu option "Email Docs & Record& not appear.

I am using Alfresco 4.2f and the latest pre-compiled modules avaliable here http://www.jumpingbean.biz/alfresco-email-documents-action-project

**Comment by mxc** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Ricardo,

Thanks for trying out the module. Is it possible to send the relevant
output from the alfresco.log files?

I cannot say from your description what the problem could be. I can
only assume the repository module did not install and that is why they
action menu is not available to share.

Once the repository module has been deployed then the share module
should work.

regards

Mark

On 28/05/2014 15:57, Ricardo wrote:

> I have installed the module following this instructions here: 
> http://www.jumpingbean.biz/alfresco-email-documents-action-project
> 
> The installation worked fine. Only a message "Unable to load
> module details from property file" appears when installing the
> module "Alfresco Repository. But I ignored the message.
> 
> When I accessed Alfresco Share and added the aspects "Email
> Template" and "Enable email document action", after I clicked in
> Apply Changes, the message could not update aspects appeared. The
> menu option "Email Docs & Record& not appear.
> 
> I am using Alfresco 4.2f and the latest pre-compiled modules
> avaliable here
> http://www.jumpingbean.biz/alfresco-email-documents-action-project
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/mxc/alfresco-emaildocuments-share/issues/3.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBCgAGBQJTidAEAAoJEM+E/JKBmb2D2L4IALkYVMKNSmQ3s4u3W0Vj8Ctx
aNQRAWw/6gQ8Mt2a7SnMkzNhcLsfJHDAou0V/Pv9KA4bghiR0KyBMnbSX1WMm+wx
jzQGWP+6JozjTjOuTVW9AuPFUPIkeARe2uLwDgoWGfgDZh20JzN9rZ2xXOtXAXYO
P4C67Au68JK3iguyGil98TkSzIeApbrWbaz2zj02PLNAXQ+cm0FstMBjwfGk3TX1
0a33ihVgxA/Wahk3jrH5ARHeLnFcOmWtEczJx9edRxHNs4teCvIxjAfS0D+8wUfb
ZxRj5R6Bygq6iActiaKwrw4XRiWVEp60I7hlylg+uwY1JYzizD2QSD/ydp5Ducc=
=Tadf
-----END PGP SIGNATURE-----

**Comment by rgiaviti** [comment]
Thanks Mark!

I have made some mistakes while intalling the module. Now it's working absolutely fine. Good job, and thank you again!

Regards,

Ricardo

**Comment by mxc** [comment]
Thanks for the feedback. Glad you getting value from it.
